# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Hölzer Lab
email: hoelzer.martin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hölzer Bioinformatics Lab.
baseurl: ""
url: ""
twitter_username: MartinHoelzer
github_username:  hoelzer

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

production_url : https://hoelzer-lab.github.io
BASE_PATH : https://hoelzer-lab.github.io

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

exclude : ["trash"]